{{- if .Values.image.pullSecrets.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-creds-harbor
  labels:
{{ include "internalalertsystem.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }} 
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internalalertsystem.fullname" . }}
  labels:
{{ include "internalalertsystem.labels" . | indent 4 }}
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  smtp_username: {{ .Values.secrets.smtp.username | b64enc | quote }}
  smtp_password: {{ .Values.secrets.smtp.password | b64enc | quote }}