{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "internalalertsystem.serviceAccountName" . }}
  labels:
{{ include "internalalertsystem.labels" . | indent 4 }}
{{- end -}}
