#https://www.collaboraoffice.com/code/docker/
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wopi
  name: wopi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wopi
  template:
    metadata:
      labels:
        app: wopi
    spec:
      nodeSelector:
        kubernetes.io/instance-life-cycle: common
      tolerations:
      - key: node.kubernetes.io/dedicated
        value: common
        effect: NoSchedule
        operator: Equal
      containers:
      - image: collabora/code
        name: code
        env:
          - name: username
            value: admin
          - name: extra_params
            value: "--o:ssl.enable=false"
          - name: password
            value: S3cRet
          - name: domain
            value: ''
        ports:
        - containerPort: 9980
---
apiVersion: v1
kind: Service
metadata:
  name: wopi
spec:
  selector:
    app: wopi
  type: NodePort
  ports:
    - protocol: TCP
      port: 9980
      targetPort: 9980
      nodePort: 30007
