apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: nginx-test
  labels:
    app: nginx-test-pod
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: nginx-test-pod
