apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
  namespace: nginx-test
  labels:
    app: nginx-test-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx-test-con
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-vol
    persistentVolumeClaim:
      claimName: nginx-vol-claim
